apiVersion: apps/v1
kind: Deployment
metadata:
  name: ServiceName
  labels:
    app: ServiceName
    deployon: "dsr"
spec:
  replicas: replace_replicas
  selector:
    matchLabels:
      app: ServiceName
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ServiceName
        deployon: "dsr"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ServiceName
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: image_to_be_deployed
        imagePullPolicy: Always
        name: ServiceName
        ports:
        - containerPort: 9100
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9100
          initialDelaySeconds: 120
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9100
          initialDelaySeconds: 60
          periodSeconds: 5
        resources:
          requests:
            memory: "1Gi"
            cpu: "2"
          limits:
            memory: "2Gi"
            cpu: "4"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: JAEGER_COLLECTOR_URL
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: jaeger.collector.url
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                name: mongodb-urls
                key: edianalyticsdata.mongodb.url
          - name: UMBRELLA_ID_VALUE
            valueFrom:
              secretKeyRef:
                name: thirdparty-passwd
                key: umbrella.id.value
          - name: EDI_CONFIG_URL
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: edi.config.url
          - name: ALL_CONFIGS_URL
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: all.configs.url     
          - name: EDI_ANALYTICS_DATA_URL
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: edi.analytics.data.url
          - name: KAFKA_BOOTSTRAP_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: replace_logical_env.kafka.bootstrap.server.url
          - name: KAFKA_TOPIC_HEADEROB
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: replace_logical_env.kafka.topic.outbound          
          - name: KAFKA_TOPIC_HEADERIB
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: replace_logical_env.kafka.topic.inbound
          - name: KAFKA_TOPIC_ANALYTICS
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: replace_logical_env.kafka.analytic.topic
          - name: BACKLOG_CRON_EXPRESSION
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: backlog.cron.expression
          - name: KAFKA_GROUPID
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: kafka.groupid
          - name: KAFKA_MAX_MESSAGE_SIZE
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: kafka.max.request.size
          - name: KAFKA_OUTBOUND_FILE_ROOTKEY
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: kafka.outbound.file.rootKey
          - name: KAFKA_OUTBOUND_FILE_SECONDARYROOTKEY
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: kafka.outbound.file.secondaryRootKey
          - name: KAFKA_OUTBOUND_FILE_NODEKEY
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: kafka.outbound.file.nodeKey
          - name: KAFKA_OUTBOUND_FILE_SECONDARYNODEKEY
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: kafka.outbound.file.secondaryNodeKey
          - name: TRX_NUMBER_FIELD
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: trx.number.field
          - name: CUSTOMER_ID_FIELD
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: customer.id.field          
          - name: LINE_COUNT_FIELD
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: line.count.field
          - name: TAX_COUNT_FIELD
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: tax.count.field
          - name: ALLOWANCE_COUNT_FIELD
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: allowance.count.field
          - name: PROCESS_FLAG_FIELD
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: process.flag.field
          - name: LINE_NUMBER_FIELD
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: line.number.field
          - name: DOCUMENT_TYPE_FIELD
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: document.type.field 
          - name: BACKLOG_COLLECTION
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: backlog.collection
          - name: LINE_COLLECTION
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: line.collection
          - name: TAX_COLLECTION
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: tax.collection
          - name: ALLOWANCE_COLLECTION
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: allowance.collection
          - name: KAFKA_SECURITY_PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: ediinvoicelistener-configmap
                key: kafka.security.protocol
          - name : SSL_TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kafka.broker.certs
                key: keystore.pwd
          - name : SSL_TRUSTSTORE_LOCATION
            value: /etc/certs/kafka/kafka.broker.keystore.jks 
        volumeMounts:
          - mountPath: /etc/certs/kafka
            name: certs
            readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: kafka.broker.certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: SvcName
  labels:
    app: ServiceName
    k8s-app: ediinvoicelistener
spec:
  selector:
    app: ServiceName
  type: ClusterIP
  ports:
  - port: 9100
    name: web
    targetPort: 9100
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler 
metadata: 
  name: ediinvoicelistener
spec: 
  maxReplicas: replace_maxReplicas
  minReplicas: replace_minReplicas 
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: hpaSrvName
  metrics: 
  - type: Resource 
    resource: 
      name: cpu
      targetAverageUtilization: 70
